--- 

- name: Rust development installation
  become: true   
  become_method: sudo   
  xbps:     
    upgrade: yes
    force: yes
    name:       
      - cargo
      - rust
      - rustup

- name: Rust install stable toolchain
  shell: rustup install stable

- name: Rust set stable toolchain
  shell: rustup default stable

- name: Rust Update 
  become: true   
  become_method: sudo
  shell: rustup update


