---

- name: Install customization packages
  
  become_method: sudo
  xbps:
    pkg:
      - ImageMagick
      - ffmpeg
      - oomox
      - lightdm
      - lightdm-gtk3-greeter
      - lightdm-webkit-greeter
      - dunst
      - i3lock
      - xscreensaver
      - caffeine-ng

- name: Install Pywal
  become: true
  pip:
    executable: pip3
    name: pywal wal_steam

