---

- name: Install customization packages
  xbps:
    pkg:
      - ImageMagick
      - ffmpeg
      - oomox
      - lightdm
      - lightdm-gtk3-greeter
      - lightdm-webkit-greeter
      - dunst
      - i3lock
      - xscreensaver
      - caffeine-ng


name: pywal
  pip:
    executable: pip3
    name: wal wal_steam

