---

- name: Install Flatpak 
  become: true   
  become_method: sudo
  xbps:
    pkg:
      - flatpak
  state: present

- name: Install Flathub repo
  become: true   
  become_method: sudo
  shell: "flatpak remove-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"

- name: Installing Steam
  become: true   
  become_method: sudo
  shell: "flatpak install flathub com.valvesoftware.Steam"
