---

- name: Install Flatpak 
  become: true   
  become_method: sudo
  xbps:
    pkg:
      - flatpak
  state: present
  register: result

- name: Install Flathub repo
  when: result|success
  shell: "flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo"

  # https://flathub.org/repo/flathub.flatpakrepo

- name: Installing Steam
  when: result|success
  shell: "flatpak --user install flathub com.valvesoftware.Steam -y"
