---

- name: Clone scripts
  git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: ~/Git/

- name: Install scripts
  shell: ~/Git/nerd-fonts/install.sh 
  with-items:
    - "{{ fonts }}"