---
- name: Install various shell packages
  xbps:
    pkg:
      - Thunar
      - ranger
      - rofi
      - albert
      - zathura

- name: Install scripts
  git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: ~/Git/
  shell: "~/Git/nerd-fonts/install.sh $FONTNAMES"
  
