---
- name: Mergerfs installation
  become: true
  become_method: sudo
  xbps:
    name:
      - mergerfs 
      - fuse
  state: present

- name: Parted installation
  become: true
  become_method: sudo
  xbps:
    name:
      - parted
  state: present

#- name: Read device information (always use unit when probing)
#  become: true
#  become_method: sudo
#  parted: device=/dev/sd"{{ item }}" unit=MiB
#  register: info
#  with_items: "{{ devices }}"

#- name: Remove all partitions from /dev/sd"{{ item.dev }}"
#  become: true
#  become_method: sudo
#  parted:
#    device: "/dev/sd{{ item.name }}"
#    number: "{{ item.partitions.num }}"
#    state: absent
#  with_items: "{{ info }}"

#- name: Create a new primary partition on "/dev/sd{{ item }}"
#  become: true
#  become_method: sudo
#  parted:
#    device: "/dev/sd{{ item }}"
#    number: 1
#    state: present
#    label: gpt
#  with_items: "{{ devices }}"

#- name: Create a ext4 filesystem on /dev/sd"{{ item }}1"
#  become: true
#  become_method: sudo
#  filesystem:
#    fstype: ext4
#    dev: "/dev/sd{{ item }}1"
#    opts: -cc
#  with_items: "{{ devices }}"


- name: Add drive mount directories
  become: true
  become_method: sudo
  file: 
    path: "/mnt/data{{ item }}" 
    state: directory
  with_items: "{{ devices }}"

- name: Add storage directory
  become: true
  become_method: sudo
  file: 
    owner: nobody
    group: nogroup
    path: /mnt/storage 
    state: directory
    mode: 0755

- name: Add fstab mount disk entries
  become: true
  become_method: sudo
  mount:
    name: "/mnt/data{{ item }}"
    src: "/dev/sd{{ item }}1"
    opts: defaults,use_ino,errors=remount-ro
    fstype: ext4
    state: mounted
  with_items: "{{ devices }}"

- name: Add fstab storage entry
  become: true
  become_method: sudo
  mount:
    name: /mnt/storage
    src: "/mnt/data*"
    opts: defaults,allow_other,use_ino,hard_remove
    fstype: fuse.mergerfs
    state: mounted
  #with_items: "{{ devices }}"