---
- name: Mergerfs installation
  xbps:
    name:
      - mergerfs 
  state: present

- name: Create a ext4 filesystem on /dev/sd"{{ item }}"
  filesystem:
    fstype: ext4
    dev: /dev/sd"{{ item }}"
    opts: -cc
  loop:
    - a
    - b
    - c


- name: Add drive mount directories
  file: path=/mnt/data"{{ item }}" state=directory
  loop:
    - 0
    - 1
    - 2

- name: Add storage directory
  file: path=/storage state=directory

- name: Add fstab mount disk entries
  lineinfile:
        path: /etc/fstab
        line: /dev/sd"{{ item.device }}" /mnt/data"{{ item.num }}"      auto   defaults,nobootwait,errors=remount-ro 0       2
  loop: 
    - { num: 0, device: a }
    - { num: 1, device: b }
    - { num: 2, device: c }

- name: Add fstab storage entry
  lineinfile:
    path: /etc/fstab
    line: /mnt/data*  /storage  fuse.mergerfs  defaults,allow_other,direct_io,moveonenospc=true  0  0x