---
- name: Mergerfs installation
  xbps:
    name:
      - mergerfs 
  state: present

- name: Create a ext4 filesystem on /dev/sd"{{ item }}"
  filesystem:
    fstype: ext4
    dev: /dev/sd"{{ item }}"
    opts: -cc
  with_items: "{{ devices }}"


- name: Add drive mount directories
  file: path=/mnt/data"{{ item }}" state=directory
  with_items: "{{ devices }}"

- name: Add storage directory
  file: path=/storage state=directory

- name: Add fstab mount disk entries
  lineinfile:
        path: /etc/fstab
        line: /dev/sd"{{ item }}" /mnt/data"{{ item }}"      auto   defaults,nobootwait,errors=remount-ro 0       2
  with_items: "{{ devices }}"

- name: Add fstab storage entry
  lineinfile:
    path: /etc/fstab
    line: /mnt/data"{{ item }}"  /storage  fuse.mergerfs  defaults,allow_other,direct_io,moveonenospc=true  0  0x
  with_items: "{{ devices }}"