---
- name: Mergerfs installation
  become: true
  become_method: sudo
  xbps:
    name:
      - mergerfs 
      - fuse
  state: present

- name: Create a ext4 filesystem on /dev/sd"{{ item }}"
  filesystem:
    fstype: ext4
    dev: "/dev/sd{{ item }}"
    opts: -cc
  with_items: "{{ devices }}"


- name: Add drive mount directories
  file: path=/mnt/data"{{ item }}" state=directory
  with_items: "{{ devices }}"

- name: Add storage directory
  file: path=/storage state=directory

- name: Add fstab mount disk entries
  mount:
    name: /mnt/data"{{ item }}"
    src: /dev/sd"{{ item }}"
    opts: defaults,allow_other,use_ino,errors=remount-ro
    fstype: ext4
    state: mounted
  with_items: "{{ devices }}"

- name: Add fstab storage entry
  mount:
    name: /mnt/storage
    src: /mnt/data"{{ item }}"
    opts: defaults,allow_other,use_ino,hard_remove
    fstype: fuse.mergerfs
    state: mounted
  with_items: "{{ devices }}"