---

- name: Get VirtualBox link   
  shell: virtualbox_latest.sh
  register: virtualbox_link

- name: Download VirtualBox  
  get_url:
    url: virtualbox_link
    dest: virtualbox.run
    mode: 0755

- name: Install VirtualBox   
  become: true   
  become_method: sudo   
  shell: ./virtualbox.run


- name: Get Vagrant link   
  shell: vagrant_latest.sh
  register: vagrant_link

- name: Download Vagrant  
  get_url:
    url: vagrant_link
    dest: vagrant.tar.xz
    mode: 0755

# - name: Download kernel headers
# linux4.16-headers-4.16.4_2
# or linux-headers-`uname -r`
# gcc make perl
