--- 
- name: Python development installation
  become: true   
  become_method: sudo   
  xbps:            
    name:
      - python3
      - python3-setuptools
      - python3-flake8
      - python3-pip
      - python3-devel
      - python
      - python-pip
    state: present

- name: Python component installation
  pip:
    executable: pip2
    name: python-language-server[all]
