--- 
- name: Python development installation
  become: true   
  become_method: sudo   
  xbps:            
        - python3
        - python3-setuptools
        - python3-flake8
        - python3-pip
	- python3-devel
        state: present

  pip:
    executable: pip2
    name: python-language-server[all]
