---

- name: Pull docker images
  become: true   
  become_method: sudo
  docker_image:
    name: 
      - "{{ item }}"
  with_items:
    - linuxserver/transmission
    # - linuxserver/jackett
    # - linuxserver/sonarr
    # - linuxserver/radarr
    # - linuxserver/lidarr
    # - linuxserver/ombi
    # - plexinc/pms-docker
    # - portainer/portainer
    # - linuxserver/heimdall
    # - linuxserver/tautulli

- name: ffmpeg installation
  xbps:
    name:
      - ffmpeg 
  state: present

- name:  Download Sickbeard Mp4 Automator
  git:
    repo: https://github.com/mdhiggins/sickbeard_mp4_automator.git
    dest: ~/Git/

- name:  Download Sickbeard Mp4 Automator dependencies
  pip:
    executable: pip2
    name:
      - setuptools
      - requests
      - requests[security]
      - requests-cache
      - babelfish
      - "guessit<2"
      - "subliminal<2"
      - python-dateutil
      - deluge-client
      - qtfaststart
    state:  present

- name: Uninstall stevedore
  pip:
    executable: pip2
    name: stevedore
    state: absent

- name: Install stevedore 1.19.1
  pip:
    executable: pip2
    name: stevedore
    version: 1.19.1
    state: present

- name: Install gevent for Deluge daemon
  pip:
    executable: pip2
    name: gevent
    state: present

- name: 
  template:
    src: autoProcess.ini.j2
    dest: ~/Git/sickbeard_mp4_automator/autoProcess.ini
