---

#- name: Pull docker images
  #become: true   
  #become_method: sudo
  #docker_image:
  #  name: 
  #    - "{{ item }}"
  #with_items:
    #- linuxserver/transmission
    # - linuxserver/jackett
    # - linuxserver/sonarr
    # - linuxserver/radarr
    # - linuxserver/lidarr
    # - linuxserver/ombi
    # - plexinc/pms-docker
    # - portainer/portainer
    # - linuxserver/heimdall
    # - linuxserver/tautulli

- name: ffmpeg installation
  become: true
  become_method: sudo
  xbps:
    name:
      - ffmpeg 
  state: present

- name:  Download Sickbeard Mp4 Automator dependencies
  become: true
  become_method: sudo
  pip:
    executable: pip2
    name:
      - setuptools
      - requests
      - requests[security]
      - requests-cache
      - babelfish
      - "guessit<2"
      - "subliminal<2"
      - python-dateutil
      - deluge-client
      - qtfaststart
    state:  present

- name: (Sickbeard dependencies) Uninstall stevedore
  become: true
  pip:
    executable: pip2
    name: stevedore
    state: absent

- name: (Sickbeard dependencies) Install stevedore 1.19.1
  become: true
  pip:
    executable: pip2
    name: stevedore
    version: 1.19.1
    state: present

#- name: Install gevent for Deluge daemon
#  become: true
#  pip:
#    executable: pip2
#    name: gevent
#    state: present

- name:  Download Sickbeard Mp4 Automator
  git:
    repo: https://github.com/mdhiggins/sickbeard_mp4_automator.git
    dest: ~/Git/sickbeard_mp4_automator

- name: Create autoProcess
  template:
    src: autoProcess.ini.j2
    dest: ~/Git/sickbeard_mp4_automator/autoProcess.ini

- name: Create docker directory
  become: true
  become_method: sudo
  file: 
    path: " {{ storage }}/docker/"
    state: directory
    owner: sudo
    group: sudo
    mode: 0755

- name: Create docker-compose
  become: true
  become_method: sudo
  template:
    src: "docker-compose.yml.j2"
    dest: " {{ storage }}/docker/docker-compose.yml"

- name: Create Traefik directory
  become: true
  become_method: sudo
  file:
    path: /opt/traefik
    state: directory

- name: Create Traefik acme.json
  become: true
  become_method: sudo
  file:
    path: /opt/traefik/acme.json
    state: touch
    mode: 0600

- name: Create Traefik traefik.toml
  become: true
  become_method: sudo
  template:
    src: "traefik.toml.j2"
    dest: "/opt/traefik/traefik.toml"