--- 

- name: Rust development installation
  become: true   
  become_method: sudo   
  xbps:     
    upgrade: yes
    name:       
      - rust-doc
      - rustfmt

- name: Rust Update 
  become: true   
  become_method: sudo
  shell: rustup update

- name: Rust components installation 
  become: true   
  become_method: sudo   
  shell: rustup component add rls-preview rust-analysis rust-src

- name: Rust Language Server 
  shell: cargo install rls --force
